config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  # VERB , to: controller#action
  # Pages routes
  get 'acerca' => 'pages#acerca'
  get 'garantia' => 'pages#garantia'
  get 'aviso_de_privacidad' => 'pages#aviso_de_privacidad'
  get 'preguntas_frecuentes' => 'pages#preguntas_frecuentes'
  get 'terminos_de_servicio' => 'pages#terminos_de_servicio'
  get 'careers' => 'pages#careers'
  get 'arrendador' => 'pages#arrendador'
  get 'arrendatario' => 'pages#arrendatario'

  # Profile routes
  get '/profile/:id', to: 'profile#show'
  get 'perfil' => 'profile#perfil'
  get 'dashboard' => 'profile#dashboard'
  get 'articulos' => 'profile#articulos'
  get 'solicitudes' => 'profile#solicitudes'
  get 'inbox' => 'profile#inbox'

  # product routes
  resources :products
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_one_attached :photos

  # validates_presence_of :column1, :column2

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products
  has_one_attached :profile_picture

  # validates :name, on: :create, message: "can't be blank"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_surgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # # Pundit: white-list approach
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name last_name mothers_last_name cellphone_number birthday rfc drop_off_location about bb_coun_try_code neighborhood zip_code city state bb_coun_try])

    devise_parameter_sanitizer.permit(:account_update, keys: %i[name last_name mothers_last_name cellphone_number birthday rfc drop_off_location about bb_coun_try_code neighborhood zip_code city state bb_coun_try])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end


# BACK UP CODE FOR APPLICATION CONTROLLER

# class ApplicationController < ActionController::Base
#   # before_action :configure_permitted_parameters, if: :devise_controller?
#   before_action :authenticate_user!

#   include Pundit

#   # Pundit: white-list approach
#   after_action :verify_authorized, except: :index, unless: :skip_pundit?
#   after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

#   # def configure_permitted_parameters
#   #   devise_parameter_sanitizer.permit(:sign_up, keys: %i[name last_name mothers_last_name])

#   #   devise_parameter_sanitizer.permit(:account_update, keys: %i[name last_name mothers_last_name])
#   # end

#   private

#   def skip_pundit?
#     devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
#   end
# end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :configure_permitted_parameters, only: :home
  skip_before_action :authenticate_user!, only: %i[home acerca garantia aviso_de_privacidad preguntas_frecuentes
                                                   terminos_de_servicio careers arrendador arrendatario]

  def home; end

  def acerca; end

  def garantia; end

  def aviso_de_privacidad; end

  def preguntas_frecuentes; end

  def terminos_de_servicio; end

  def careers; end

  def arrendador; end

  def arrendatario; end

  

 
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  # authorize @product

  def index
    # @products = Product.all
    @products = policy_scope(Product).order(created_at: :desc)
  end

  def show; end

  def new
    @product = Product.new
    authorize @product
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    authorize @product

    if @product.save
      redirect_to @product, notice: 'El producto fue agregado exitosamente.'
    else
      render :new
    end
  end

  def edit; end

  def update
    @product.update(product_params)
  end

  def destroy
    @product.destroy

    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:photos, :title, :daily_price, :weekly_price, :monthly_price, :description)
  end

  def set_product
    @product = Product.find(params[:id])
    authorize @product
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
   def perfil
    @nombre = nombre
    @apellido_paterno = apellido_paterno
    @apellido_materno = apellido_materno
    @fecha_de_union_a_bibi = fecha_de_union_a_bibi
    @cumpleanos = cumpleanos
    @telefono = telefono
    @direccion_completa = direccion_completa
    @acerca_de_mi = acerca_de_mi
    @nombre_cuenta = nombre_cuenta
    @direccion = direccion
    @colonia = colonia
    @codigo_postal = codigo_postal
    @ciudad = ciudad
    @estado = estado
    @pais = pais
    @rfc = rfc
  end

  def dashboard; end

  def articulos; end

  def solicitudes;  end

  def inbox; end
  

  private

  ########### Pefil Methods ###########

  def nombre
    current_user.name || "Nombre."
  end

  def apellido_paterno
    current_user.last_name || "Apellido paterno."
  end

  def apellido_materno
    current_user.mothers_last_name || "Apellido materno."
  end

  def mes_union_bibi
    current_user.created_at.month
  end

  def fecha_de_union_a_bibi
    current_user.created_at.strftime("#{written_month(mes_union_bibi)}/%Y")
  end

  def mes_nacimiento
    current_user.birthday ? current_user.birthday.month : nil
  end

  def fecha_nacimiento
    current_user.birthday
  end

  def cumpleanos
    fecha_nacimiento ? "#{fecha_nacimiento.day}/#{written_month(mes_nacimiento)}/#{fecha_nacimiento.year}" : "Aún no nos has dicho tu cumpleaños."
  end

  def telefono
    "+#{current_user.bb_coun_try_code} #{current_user.cellphone_number}"
  end

  def direccion
    current_user.drop_off_location || "Agregar calle y número."
  end

  def colonia
    current_user.neighborhood || "Agrega tu colonia."
  end

  def codigo_postal
    current_user.zip_code || "Agrega tu código postal."
  end

  def estado
    current_user.state || "Ingresa tu estado."
  end

  def direccion_completa
    "#{direccion}, Col. #{colonia}, C.P.: #{codigo_postal}, #{estado}"
  end

  def acerca_de_mi
    current_user.about || "Aquí puedes agregar información acerca de tí."
  end

  def written_month(number)
    month = nil
    case number
    when 1 then month = "Ene"
    when 2 then month = "Feb"
    when 3 then month = "Mar"
    when 4 then month = "Abr"
    when 5 then month = "May"
    when 6 then month = "Jun"
    when 7 then month = "Jul"
    when 8 then month = "Ago"
    when 9 then month = "Sep"
    when 10 then month = "Oct"
    when 11 then month = "Nov"
    when 12 then month = "Dic"
    end
    month
  end

  ########### Cuenta Methods ###########

  def nombre_cuenta
    current_user.name ? "#{nombre} #{apellido_paterno.chars.first}" : "Agrega tu nombre y apellidos por favor."
  end

  def ciudad
    current_user.city || "Agrega tu ciudad a tu perfil."
  end

  def pais
    current_user.bb_coun_try || "Agrega tu país."
  end

  def rfc
    current_user.rfc || "Es necesario agregar tu RFC para rentar productos."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/layouts/_show.html.erb
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#showModalScrollable" >
  Launch demo modal
</button>

<div class="modal fade" id="showModalScrollable"  tabindex="-1" aria-hidden="true">
  <div class="shomodalcont modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="comp-tit">
          <h2>Vive la experiencia</h2>
      </div>
        
          <%= link_to 'x', products_path %>
     
      </div>
      <div class="modal-body">    
    <div class="modinfcon">
      <div class="modinfgen">
        <div class="modinffot"><%# <%= cl_image_tag @product.photo.key, height: 300, width: 400, crop: :fill %>  
          <div class="fotpri">
            Foto principal (1)
          </div>
          <div class="fotsec">
            <div class="fotsectod">
              Fotos secundarias no.1
            </div>
            <div class="fotsectod">
              Fotos secundarias no.2
            </div>
            <div class="fotsectod">
              Fotos secundarias no.3
            </div>
            <div class="fotsectod">
              Fotos secundarias no.4
            </div>
          </div>
        </div>

        <div class="modinfpro">
          <h4>Información</h4>
        </div>
        <div class="modinfcat">
          Categoria/Subcategoria/Artículo    
        </div>

    <div class="shosubtit">
          <h4>Descripción del artículo</h4>
    </div>

        <div class="modinfdes">
          <p> <%= @product.description %> </p>
        </div>

          <h4>Arrendador</h4>

        <div class="modinfper">
          <img class="modinfperava"src="https://res.cloudinary.com/dfy5vakwb/image/upload/v1631294724/bibi/_MG_0046_p8vijw.jpg" alt="">
          <div class="modinfperizq">
            <p> Diego G.</p>
            <p> Ciudad de México </p>
          </div>
          <div class="modinfpreder">
            <p>Calificación xxxxx</p>
            <p>Artículos 34</p>
          </div>
        </div>
    <div class="shosubtit">
          <h4>Entregas</h4>
    </div>
        <div class="modinfubi">
          <div class="modinfubiizq">
            <div class="modubi">
              <p> Opcion 1</p>
              <p> Roma norte </p>
            </div>
            <div class="modubi">
              <p> Opción 2</p>
              <p> Roma sur </p>
            </div>
          </div>
          <div class="modinfubider">
            <div class="modubimap">
              <p> Mapa 1</p>
            </div>
            <div class="modubimap">
              <p> Mapa 2</p>
            </div>
          </div>
        </div>

    <div class="shosubtit">
      <h4>Reviews</h4>
    </div>

        <div class="modinfrev">
          <div class="modinfrevcom">
            <div class="modrevarr">
              <p> Arrendatario</p>
              <p> Comentario </p>
            </div>
            <div class="modrevcal">
              <p> Calificación</p>
              <p> Calificación</p>
            </div>   
          </div>
        </div>

    <div class="shosubtit">
      <h4>Más artículos</h4>
    </div>

    <div class="shocarcon">

      <%#@products.each do |product| %>

      <div class="shocarprod"> <%#Show Card Products%>
        <div class="shoimgcon">
          <a href="">
          <%#Top Image Products%>
            <img class="shoimgprod" src="https://res.cloudinary.com/dfy5vakwb/image/upload/c_scale,h_130,w_180/v1633666923/bibi/Products.Pictures/drone_tdft5t.jpg" alt="">
        </div>
          <div class="shcartit"> <%#Show card Title Products%>
            <p class="shocarfon"> <%#Show card Product Title Font%>
            Dron DJI Mavic 2019 + baterias y control
            <%#= link_to "#{product.title}", product_path(product) %>
            </p> 
          </div>
          <div class="shocarowninf"> <%#Show card Info Owner%>
            <div class="shoinfprod"> <%#Show card Info Product%>
              <div class="showowl"> <%#Show card Owner Level%>
                <i class="fas fa-bolt fa-sm"></i>
              </div>
              <div class="shoownam"> <%#Show card Owner Name%>
                <p class="shoownamfon"> Diego G.<%#= "#{product.user.name} #{product.user.last_name}." %> </p>
              </div>
            </div>
            <div class="shoprostarev">
              <div class="shoprodstico"> <%#Show card Product Stars Icons%>
                <i class="fas fa-star fa-xs"></i><i class="fas fa-star fa-xs"></i><i class="fas fa-star fa-xs"></i><i class="fas fa-star fa-xs"></i><i class="fas fa-star fa-xs"></i>
              </div>
              <div class="shoprodstav"> <%#Show card Products Stars Average%>
                <p class="shoprorev">(47)</p> <%#Show card Product reviews%>
              </div>
            </div>
          </div>
            <div class="shopropri"><%#Show card products Price%>
              <p class="shoprifon">
              $1,200
                <%#= "$ #{product.daily_price}" %>
              </p>
              <p>/día</p> <%#Show card Price Font%>
            </div>
          </a>
        </div>
      <%# end %>
      <%#@products.each do |product| %>

      <div class="shocarprod"> <%#Show Card Products%>
        <div class="shoimgcon">
          <a href="">
          <%#Top Image Products%>
            <img class="shoimgprod" src="https://res.cloudinary.com/dfy5vakwb/image/upload/c_scale,h_130,w_180/v1633666923/bibi/Products.Pictures/drone_tdft5t.jpg" alt="">
        </div>
          <div class="shcartit"> <%#Show card Title Products%>
            <p class="shocarfon"> <%#Show card Product Title Font%>
            Dron DJI Mavic 2019 + baterias y control
            <%#= link_to "#{product.title}", product_path(product) %>
            </p> 
          </div>
          <div class="shocarowninf"> <%#Show card Info Owner%>
            <div class="shoinfprod"> <%#Show card Info Product%>
              <div class="showowl"> <%#Show card Owner Level%>
                <i class="fas fa-bolt fa-sm"></i>
              </div>
              <div class="shoownam"> <%#Show card Owner Name%>
                <p class="shoownamfon"> Diego G.<%#= "#{product.user.name} #{product.user.last_name}." %> </p>
              </div>
            </div>
            <div class="shoprostarev">
              <div class="shoprodstico"> <%#Show card Product Stars Icons%>
                <i class="fas fa-star fa-xs"></i><i class="fas fa-star fa-xs"></i><i class="fas fa-star fa-xs"></i><i class="fas fa-star fa-xs"></i><i class="fas fa-star fa-xs"></i>
              </div>
              <div class="shoprodstav"> <%#Show card Products Stars Average%>
                <p class="shoprorev">(47)</p> <%#Show card Product reviews%>
              </div>
            </div>
          </div>
            <div class="shopropri"><%#Show card products Price%>
              <p class="shoprifon">
              $1,200
                <%#= "$ #{product.daily_price}" %>
              </p>
              <p>/día</p> <%#Show card Price Font%>
            </div>
          </a>
        </div>
      <%# end %>
      <%#@products.each do |product| %>

      <div class="shocarprod"> <%#Show Card Products%>
        <div class="shoimgcon">
          <a href="">
          <%#Top Image Products%>
            <img class="shoimgprod" src="https://res.cloudinary.com/dfy5vakwb/image/upload/c_scale,h_130,w_180/v1633666923/bibi/Products.Pictures/drone_tdft5t.jpg" alt="">
        </div>
          <div class="shcartit"> <%#Show card Title Products%>
            <p class="shocarfon"> <%#Show card Product Title Font%>
            Dron DJI Mavic 2019 + baterias y control
            <%#= link_to "#{product.title}", product_path(product) %>
            </p> 
          </div>
          <div class="shocarowninf"> <%#Show card Info Owner%>
            <div class="shoinfprod"> <%#Show card Info Product%>
              <div class="showowl"> <%#Show card Owner Level%>
                <i class="fas fa-bolt fa-sm"></i>
              </div>
              <div class="shoownam"> <%#Show card Owner Name%>
                <p class="shoownamfon"> Diego G.<%#= "#{product.user.name} #{product.user.last_name}." %> </p>
              </div>
            </div>
            <div class="shoprostarev">
              <div class="shoprodstico"> <%#Show card Product Stars Icons%>
                <i class="fas fa-star fa-xs"></i><i class="fas fa-star fa-xs"></i><i class="fas fa-star fa-xs"></i><i class="fas fa-star fa-xs"></i><i class="fas fa-star fa-xs"></i>
              </div>
              <div class="shoprodstav"> <%#Show card Products Stars Average%>
                <p class="shoprorev">(47)</p> <%#Show card Product reviews%>
              </div>
            </div>
          </div>
            <div class="shopropri"><%#Show card products Price%>
              <p class="shoprifon">
              $1,200
                <%#= "$ #{product.daily_price}" %>
              </p>
              <p>/día</p> <%#Show card Price Font%>
            </div>
          </a>
        </div>
      <%# end %>
      <%#@products.each do |product| %>

      <div class="shocarprod"> <%#Show Card Products%>
        <div class="shoimgcon">
          <a href="">
          <%#Top Image Products%>
            <img class="shoimgprod" src="https://res.cloudinary.com/dfy5vakwb/image/upload/c_scale,h_130,w_180/v1633666923/bibi/Products.Pictures/drone_tdft5t.jpg" alt="">
        </div>
          <div class="shcartit"> <%#Show card Title Products%>
            <p class="shocarfon"> <%#Show card Product Title Font%>
            Dron DJI Mavic 2019 + baterias y control
            <%#= link_to "#{product.title}", product_path(product) %>
            </p> 
          </div>
          <div class="shocarowninf"> <%#Show card Info Owner%>
            <div class="shoinfprod"> <%#Show card Info Product%>
              <div class="showowl"> <%#Show card Owner Level%>
                <i class="fas fa-bolt fa-sm"></i>
              </div>
              <div class="shoownam"> <%#Show card Owner Name%>
                <p class="shoownamfon"> Diego G.<%#= "#{product.user.name} #{product.user.last_name}." %> </p>
              </div>
            </div>
            <div class="shoprostarev">
              <div class="shoprodstico"> <%#Show card Product Stars Icons%>
                <i class="fas fa-star fa-xs"></i><i class="fas fa-star fa-xs"></i><i class="fas fa-star fa-xs"></i><i class="fas fa-star fa-xs"></i><i class="fas fa-star fa-xs"></i>
              </div>
              <div class="shoprodstav"> <%#Show card Products Stars Average%>
                <p class="shoprorev">(47)</p> <%#Show card Product reviews%>
              </div>
            </div>
          </div>
            <div class="shopropri"><%#Show card products Price%>
              <p class="shoprifon">
              $1,200
                <%#= "$ #{product.daily_price}" %>
              </p>
              <p>/día</p> <%#Show card Price Font%>
            </div>
          </a>
        </div>
      <%# end %>
      </div>

    </div>

      <div class="modinfpre">
        <div class="modinftit">
          <h3><%= @product.title %></h3>
        </div>
        <div class="modinfpredsm">
          <h4>Precios</h4>
        <div class="modprecon">
          <div class="modpredsm">
            <h4>Diario</h4>
            <h3> <%= "$ #{@product.daily_price}" %> <span color="black">/día</span></h3>
          </div>
          <div class="modpredsm">
            <h4>+ 7 días</h4>
            <h3> <%= "$ #{@product.weekly_price}" %> <span color="black">/día</span></h3>
          </div>
          <div class="modpredsm" >
            <h4>+ 30 días</h4>
            <h3> <%= "$ #{@product.monthly_price}" %> <span color="black">/día</span></h3>
          </div>
        </div>
        <div class="modbtns">
          <button class="btnmodsol" >Rentar</button>
          <a href="">Enviar mensaje</a>
        </div>
        </div>
      </div>
      
      </div>
    </div>
    

      </div>
      
    </div>
  </div>
</div>

app/views/layouts/_signupmod.html.erb
<div class="modal" id="signupModal" tabindex="-2" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="container" id="container">
      <div class="form-container sign-up-container">
        <div class="form">
          <div class="intsignup1">
              <h1>¡Bienvenid@s!</h1>
              <p class="signupslogan" style="opacity: 40%;">Ingresa tus datos y empieza a vivir ligero.</p>
          </div>
          <div class="forinpsig">
          <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), :defaults => { :input_html => { :class => "taginput" } }) do |f| %>
          <%= f.error_notification %>
          <%= f.input :email,
                      placeholder: "Email",
                      label: false,
                      required: true,
                      autofocus: true,
                      input_html: { autocomplete: "email" }%>
          <%= f.input :cellphone_number,
                      placeholder: "No. celular",
                      label: false,
                      required: true %>
          <%= f.input :password,
                      placeholder: "Contraseña",
                      label: false,
                      required: true,
                      hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                      input_html: { autocomplete: "new-password" } %>
          <%= f.input :password_confirmation,
                      placeholder: "Confirmar contraseña",
                      label: false,
                      required: true,
                      input_html: { autocomplete: "new-password" } %>
          </div>
          <div class="btnsigininupcon">
            <button class="btnsigninup" type="submit">Registrarme</button>
            <span>o</span>
            <button class="btnsignupgo">
              <div class="btnlog">
                <%=cl_image_tag("bibi/Social.Media/google_lx0gw7.png", :height=>17, :crop=>"scale")%>
              </div>
              <div class="btntext">
                <p style="font-size:16px">Registrarme con Google</p>
              </div>
            </button>
            <p style="font-size: 12px; margin-top: 10px">Al registrarte estas aceptando <em><a href="/aviso_de_privacidad" style="color:#FFF562">aviso de privacidad </a></em> y nuestros <em><a href="/terminos_de_servicio" style="color:#FFF562">terminos y condiciones.</a></em></p>
          <% end %>
          </div>
      </div> 
      </div>
      <div class="form-container sign-in-container">
        <div class="form">
          <div class="intsignup1">
            <h1>Iniciar sesión</h1>
            <p class="signupslogan" style="opacity: 40%;">Te estabamos esperando.</p>
          </div>
          <div class="forinpsig">
            <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name),:defaults => { :input_html => { :class => "taginput" } }) do |f| %>
            <div class="form-inputs">
              <%= f.input :email,
                          label: false,
                          placeholder: "Email",
                          required: false,
                          autofocus: true,
                          input_html: { autocomplete: "email" } %>
              <%= f.input :password,
                          label: false,
                          placeholder: "Contraseña",
                          required: false,
                          input_html: { autocomplete: "current-password" } %>
              <a href="#">
                <p style="font-size: 12px; text-align: end">¿Olvidaste tu contraseña?</p>
              </a>
              <%= f.input :remember_me,
                          :input_html => { :class => 'remmebtn' },
                          label: 'Recordar contraseña' ,
                          as: :boolean if devise_mapping.rememberable? %>
            </div>
          </div>
          <div class="btnsigininupcon">
            <button class="btnsigninup">Continuar</button>
            <span>o</span>
            <button class="btnsignupgo">
              <div class="btnlog">
                <%=cl_image_tag("bibi/Social.Media/google_lx0gw7.png", :height=>17, :crop=>"scale")%>
              </div>
              <div class="btntext">
                <p style="font-size:16px">Continuar con Google</p>
              </div>
            </button>
          </div>
          <% end %>
        </div> 
      </div>
      <div class="overlay-container">
        <div class="overlay">
          <div class="overlay-panel overlay-left">
            <p style="color: black">Ya tienes cuenta.</p>
            <button class="btnghost" id="signIn">Iniciar sesión</button>
          </div>
          <div class="overlay-panel overlay-right">
            <p style="color: black" >Aun no tienes cuenta.</p>
            <button class="btnghost" id="signUp">Crear cuenta</button>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/pages/about.html.erb
<h1>Acerca de Nosotros</h1>

app/views/pages/careers.html.erb
<h1>Careers</h1>

app/views/products/edit.html.erb
<%= render "form", product: @product %>

app/views/products/new.html.erb
<%= render "form", product: @product %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="site-section">
    <div class="foocontainer">
      </div>
        <div class="gen-infofo">
          <div class="info-sect">
            <h3>Clientes</h3>
            <ul class="list-unstyled">
              <li><%= link_to "Arrendador", arrendador_path %></li>
              <li><%= link_to "Arrendatario", arrendatario_path %></li>
            </ul>
          </div>
          <div class="info-sect">
            <h3>Nosotros</h3>
            <ul class="list-unstyled">
              <li><a href="#">Nuestra misión</a></li>
              <li><%= link_to "Acerca de nosotros", acerca_path %></li>
            </ul>
          </div>
          <div class="info-sect">
            <h3>Más información</h3>
            <ul class="list-unstyled">
              <li><%= link_to "Garantia", garantia_path %></li>
              <li><%= link_to "Aviso de privacidad", aviso_de_privacidad_path %></li>
              <li><%= link_to "Preguntas frecuentes", preguntas_frecuentes_path %></li>
              <li><%= link_to "Terminos y condiciones", terminos_de_servicio_path %></li>
            </ul>
          </div>
        <div class="info-sect">
          <h3>Siguenos</h3>
          <ul class="list-unstyled social fa-2x">
            <a href=""><i class="fab fa-linkedin"></i></a>
            <a href=""><i class="fab fa-instagram"></i></a>
            <a href=""><i class="fab fa-twitter-square"></i></a>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar">

  <div class="logsba">
    <a href="/"><img class="hlogobtn" src="https://res.cloudinary.com/dfy5vakwb/image/upload/c_scale,w_80/v1630947355/bibi/logo.png" alt=""></a>
    <div class="sback">
        <input class="form-control" type="text" placeholder="Explorar...">
        <button class="sbtn"><i class="fas fa-search"></i></button>
    </div>  
  </div>
  <ul class="navbar-nav mr-auto"> 
  <div class="mentog" id="">
    
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "https://res.cloudinary.com/dfy5vakwb/image/upload/v1631294724/bibi/_MG_0046_p8vijw.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              
              <%= link_to "Perfil", perfil_path, class: "dropdown-item" %>
              <%= link_to "Inbox", inbox_path, class: "dropdown-item" %>
              <%= link_to "Artículos", articulos_path, class: "dropdown-item" %>
              <%= link_to "Solicitudes", solicitudes_path, class: "dropdown-item" %>
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item"  %>
            </div>
          </li>
          
        <% else %>
          <li class="nav-item dropdown">
            <%= image_tag "https://res.cloudinary.com/dfy5vakwb/image/upload/v1638230967/bibi/shared/Benzene_Ring_hfy45y.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Iniciar", user_session_path, class: "dropdown-item", "data-toggle" => "modal", "data-target" => "#signupModal" %>
              <%= link_to "Arrendador", arrendador_path, class: "dropdown-item"%>
              <%= link_to "Arrendatario", arrendatario_path, class: "dropdown-item"%>
            </div>
    <%end%>
  </div>
</div>